<a href="https://colab.research.google.com/github/NithinReddy215/machine-learning/blob/main/ML_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Create DataFrame Sales
data = {
    "2014": [100.5, 150.8, 200.9, 30000, 40000],
    "2015": [12000, 18000, 22000, 30000, 45000],
    "2016": [20000, 50000, 70000, 100000, 125000],
    "2017": [50000, 60000, 70000, 80000, 90000]
}
index = ["Madhu", "Kusum", "Kinshuk", "Ankit", "Shruti"]

Sales = pd.DataFrame(data, index=index)
print(Sales)


            2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000


In [ ]:
print("Row Labels:", Sales.index.tolist())


Row Labels: ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']


In [ ]:
print("Column Labels:", Sales.columns.tolist())


Column Labels: ['2014', '2015', '2016', '2017']


In [ ]:
print("Data Types:\n", Sales.dtypes)


Data Types:
 2014    float64
2015      int64
2016      int64
2017      int64
dtype: object


In [ ]:
print("Dimensions:", Sales.ndim)
print("Shape:", Sales.shape)
print("Size:", Sales.size)
print("Values:\n", Sales.values)


Dimensions: 2
Shape: (5, 4)
Size: 20
Values:
 [[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]


In [ ]:
print(Sales.tail(2))


           2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000


In [ ]:
print(Sales.iloc[:, :2])


            2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000


In [ ]:
sales2_dict = {
    "2018": {
        "Madhu": 160000,
        "Kusum": 110000,
        "Kinshuk": 500000,
        "Ankit": 340000,
        "Shruti": 900000
    }
}
Sales2 = pd.DataFrame(sales2_dict)
print(Sales2)


           2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000


In [ ]:
print("Is Sales2 empty?:", Sales2.empty)


Is Sales2 empty?: False


In [ ]:
Sales = pd.concat([Sales, Sales2], axis=1)
print(Sales)


            2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000


In [ ]:
Sales = Sales.T
print(Sales)


         Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0


In [ ]:
print(Sales.loc["2017"])


Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64


In [ ]:
print(Sales.loc[["2017", "2018"], ["Madhu", "Ankit"]])


         Madhu     Ankit
2017   50000.0   80000.0
2018  160000.0  340000.0


In [ ]:
print(Sales.loc["2016", "Shruti"])


125000.0


In [ ]:
Sales["Sumeet"] = [196.2, 37800, 52000, 78438, 38852]
print(Sales)


         Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2014     100.5     150.8     200.9   30000.0   40000.0    196.2
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0


In [ ]:
Sales = Sales.drop("2014")
print(Sales)


         Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0


In [ ]:
Sales = Sales.drop(columns="Kinshuk")
print(Sales)


         Madhu     Kusum     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
Sales = Sales.rename(columns={"Ankit": "Vivaan", "Madhu": "Shailesh"})
print(Sales)


      Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
Sales.to_csv("SalesFigures.csv", index=False, header=False)


In [ ]:
SalesRetrieved = pd.read_csv("SalesFigures.csv", header=None)

# Assign proper labels
SalesRetrieved.index = Sales.index
SalesRetrieved.columns = Sales.columns

print(SalesRetrieved)


      Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
import pandas as pd
import numpy as np

# 13a
data = {
    "Item": ["TV", "TV", "TV", "AC"],
    "Company": ["LG", "VIDEOCON", "LG", "SONY"],
    "Rupees": [12000, 10000, 15000, 14000],
    "USD": [700, 650, 800, 750]
}
Product = pd.DataFrame(data)

# 13b
new_row = {"Item": "AC", "Company": "LG", "Rupees": 16000, "USD": 820}
Product = pd.concat([Product, pd.DataFrame([new_row])], ignore_index=True)

# 13c
lg_tv = Product[(Product["Company"] == "LG") & (Product["Item"] == "TV")]
print(lg_tv["Rupees"].max())

# 13d
print(Product["Rupees"].sum())

# 13e
sony = Product[Product["Company"] == "SONY"]
print(sony["USD"].median())

# 13f
Product_sorted = Product.sort_values("Rupees")
# Product_sorted.to_sql("ProductTable", conn, if_exists='replace', index=False)

# 13g
# Product.to_sql("UpdatedProduct", conn, if_exists='replace', index=False)


15000
67000
750.0


In [ ]:
# 14a
data2 = {
    "Name": ["Aparna", "Pankaj", "Ram", "Ramesh", "Naveen", "Krrishnav", "Bhawna"],
    "Degree": ["MBA", "BCA", "M.Tech", "MBA", "MBA", "BCA", "MBA"],
    "Score": [90.0, np.nan, 80.0, 98.0, 97.0, 78.0, 89.0]
}
df = pd.DataFrame(data2)

# 14b
print(df.groupby("Degree")["Score"].max())

# 14c
df["Score"].fillna(76, inplace=True)

# 14d
df.set_index("Name", inplace=True)

# 14e
print(df[["Degree", "Score"]])

# 14f
print(df[df["Degree"] == "MBA"].shape[0])

# 14g
print(df[df["Degree"] == "BCA"]["Score"].mode())


Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
Name: Score, dtype: float64
           Degree  Score
Name                    
Aparna        MBA   90.0
Pankaj        BCA   76.0
Ram        M.Tech   80.0
Ramesh        MBA   98.0
Naveen        MBA   97.0
Krrishnav     BCA   78.0
Bhawna        MBA   89.0
4
0    76.0
1    78.0
Name: Score, dtype: float64


/tmp/ipython-input-22-3544487873.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Score"].fillna(76, inplace=True)
